#pragma once

#include <MultiLibrary/Config.hpp>

#if defined MULTILIBRARY_FILESYSTEM_EXPORT

	#define MULTILIBRARY_FILESYSTEM_API MULTILIBRARY_API_EXPORT

#else

	#define MULTILIBRARY_FILESYSTEM_API MULTILIBRARY_API_IMPORT

#endif