#pragma once

#include <MultiLibrary/Config.hpp>

#if defined MULTILIBRARY_WINDOW_EXPORT

	#define MULTILIBRARY_WINDOW_API MULTILIBRARY_API_EXPORT

#else

	#define MULTILIBRARY_WINDOW_API MULTILIBRARY_API_IMPORT

#endif